server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reserve
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: username
      password: password

mybatis:
  config-location: classpath:mybatis-config.xml

jwt:
  secret: secret
  expiration: 86400000

file:
  lua:
    reservation:
      create: /lua/create_reservation.lua
      cancel: /lua/cancel_reservation.lua