server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reserve
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml

jwt:
  secret: secret
  expiration: 86400000